# Generated by Django 5.2.6 on 2025-10-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('food_item', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('water_intake', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.typemeal')),
            ],
        ),
    ]
